# Generated by Django 5.2.6 on 2026-05-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0002_alter_userregister_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('both', 'Buyer + Seller'), ('admin', 'Admin')], max_length=20),
        ),
    ]
