# Generated by Django 5.2.6 on 2026-05-26 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0004_category_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=10)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auction_end_time', models.DateTimeField()),
                ('product_image', models.ImageField(upload_to='products/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bid.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bid.userregister')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bid.subcategory')),
            ],
        ),
    ]
