# Generated by Django 5.2.6 on 2026-05-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auction_status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('ended', 'Ended')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='bid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='current_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
