# Generated by Django 5.2.6 on 2026-05-28 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0007_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to='bid.userregister'),
        ),
    ]
