# Generated by Django 5.2.6 on 2026-05-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auction_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
