# Generated by Django 5.2.6 on 2026-05-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0010_product_auction_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_role',
            field=models.CharField(default='buyer', max_length=20),
            preserve_default=False,
        ),
    ]
