# Generated by Django 5.2.6 on 2026-05-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0011_notification_target_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='buyer', max_length=50),
            preserve_default=False,
        ),
    ]
