# Generated by Django 5.2.6 on 2026-06-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0014_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
