# Generated by Django 5.2.6 on 2026-06-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0015_product_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sold',
        ),
    ]
