# Generated by Django 5.2.6 on 2026-06-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0016_remove_product_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
