# Generated by Django 5.2.6 on 2026-06-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0017_bid_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
